# Generated by Django 5.1.4 on 2025-03-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binary_image', models.FileField(upload_to='satellite_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sea_type', models.CharField(choices=[('ЧЕРНОЕ', 'Черное Море'), ('АЗОВСКОЕ', 'Азовское Море')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binary_image', models.FileField(upload_to='processed_images/')),
                ('area_of_pollution', models.FloatField(help_text='Площадь загрязнения в квадратных километрах')),
                ('degree_of_pollution', models.FloatField(help_text='Степень уверенности модели в обнаружении (0-100)')),
                ('processing_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to=settings.AUTH_USER_MODEL)),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_versions', to='images.uploadedimage')),
            ],
        ),
    ]
